cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install torch
cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install datasets
cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install transformers
cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install faiss-cpu
cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install multiformats
cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install llama_index
cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install llama-index-embeddings-huggingface 
cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install rank_bm25
cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install qdrant-client
cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install uvicorn
cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install fastapi
cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install fastapi[standard]
cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install numpy
cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install aiohttp
cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install elasticsearch
cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install nltk
cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install -r /opt/app-root/src/laion-embeddings/requirements.txt
cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install  ovmsclient
# cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install 
# cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install 
# cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install 
# cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install 
# cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install 
# cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install 
# cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install 
# cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install 
# cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install 
# cd /opt/app-root/src/laion-embeddings ; /usr/bin/env  /bin/python3 -m pip install 